services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: evalua_frontend
    ports:
      - "8080:80"
    depends_on:
      - flutter_builder
      - backend

  flutter_builder:
    image: ghcr.io/cirruslabs/flutter:latest
    container_name: evalua_flutter_builder
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: >
      bash -c "flutter pub get &&
               flutter build web"

  backend:
    build: ./backend
    container_name: evalua_backend
    volumes:
      - ./backend:/app
    ports:
      - "8888:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/evaluaplus
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: evalua_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: evaluaplus
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
